import React from 'react'


export const metadata = {
  title: "Contact Page",
  description: "Generated by home page",
};


export default function page() {
  return (
    <div>Contact Page</div>
  )
}
