import HeroSection from '@/components/Hero';
import React from 'react'
import FoodCard from '@/components/FoodCard';
import { getRecipes } from '@/api/recipe';


export const metadata = {
    title: "Home Page",
    description: "Generated by create next app",
};

export default async function HomePage() {
    const recipes = await getRecipes();
    return (
        <>
            <div className='w-full mx-auto  my-10 px-2'>
                <div className='w-full grid grid-cols-4 gap-4'>
                    {
                        recipes.map((data, index) => {
                            return (
                                <FoodCard
                                    key={index}
                                    image={data.image}
                                    title={data.name}
                                    cuisine={data.cuisine}
                                    rating={data.rating}
                                    deliveryTime={data.cookTimeMinutes}
                                    priceForTwo="499"
                                    offer="50% OFF"
                                    id={data.id}
                                />
                            )
                        })
                    }

                </div>

            </div>


        </>
    )
}
