
import ProductCard from '@/components/ProductCard';
import axios from 'axios';
import React from 'react'

export const metadata = {
  title: "Home Page",
  description: "Generated by home page",
};

export default async function HomePage() {

  const response = await axios.get("https://dummyjson.com/products");
  const data = response.data.products;

  return (
    <div className="grid grid-cols-4">
      {
        data.map((prod, index) => {
          return (
            <ProductCard product={prod} key={index} />
          )
        })
      }
    </div>
  )
}
