import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import Sidebar from "@/components/admin/Sidebar";
import Header from "@/components/admin/Header";
import { Toaster } from 'sonner'



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body >
        <div className="w-full h-full flex">
          <Sidebar />
          <div className="flex-1">
            <Toaster position="top-right" richColors />

            <Header />
            <div className="p-4 bg-[#f7f8fd] w-full h-full">
              {children}
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
